name: Deploy PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ./doc/main.tex
      - name: Copy
        run: |
          mkdir out
          cp ./doc/main.pdf ./out/main.pdf
      - uses: actions/upload-artifact@v4
        with:
          name: exercises
          path: out/main.pdf
