name: Build LaTeX document
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: doc/
      - name: Copy
        run: |
          mkdir out
          cp doc/main.pdf out/main.pdf
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: out/main.pdf
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
